### ISSUE TITLE
[ngrx ducks] ngrx versions (discussion)

### ISSUE THREAD

**Issue by skydever** [co-IT/co-it#8]
hi there!

We were discussing the integration of the `Ducks` in our team today. I think the API is really great, if you look at a `Duck`, it is easy to understand what is going on (the decorators are a real boost in my opinion). Also for newcomers, people with less knowledge of ngrx itself (most of the team members did not work with ngrx before, some did not work with Angular before). I myself did not work with ngrx before, but read a lot of docs, blogs and watched some videos - somehow I did not like the creation of actions and reducers, but I really like the concept, the dev tools are awesome ... and the `Ducks` convinced me to give it a shot 👍 

The facade concept seems not to be used that much in *pure* **ngrx** projects (?), working directly with the store seems to be the *usual* way. Please correct me if that is not the case, but I did not came across facades that much in my research. Using the `Ducks` gives you a facade out of the box, and a downside here could be in some situations that you have to inject multiple services (ducks) instead of the `Store` only, if you need to modify multiple slices of the store - but maybe this is an advantage too? You see what parts of the store are used in a component/service etc. right at the `constructor`, and modifying multiple slices is not a *standard* use case ... but this is another topic for itself I think, to go with the facade concept or not, but fundemantal for the decision to use the `Ducks`.

There is this statement at the readme:

> You see the only API you have to work with is the Ducks-API. It does not change anything in ngrx but automates the process dealing with actions.

What does this mean in terms of version compatibility? ngrx is running under the hood, but the selectors and the effects are mostly handled in a pure ngrx way (except for how you dispatch them, `ofType`, `pick()`), as quoted. We want to stay up to date with **ngrx** (changes in Angular can require breaking changes at **ngrx** and we want to stay up to date with Angular). It would be great to have a section about version compatibility, what version of the `Ducks` are compatible with what version of **ngrx**. Can you give any statement about how you want to achieve to be compatible with *latest* ngrx versions over time, in the future? What has to happen to break the `Ducks`? It seems to be a thin layer on top of **ngrx**, and a great one in my opinion. If you look at older **ngrx** versions, how far can the `Ducks` walk back and would still work?

I like using `Ducks` and there is no problem in sight, but I also need to make sure to be future proof as good as I can.

**Comment by GregOnNet** [comment]
Hi,

I thought about this topic as well.
For now, it is simple.

The version of Ducks is aligned with ngrx.
If you use ngrx-ducks 7.x it is compatible with ngrx 7.x.

For ngrx-ducks it means we only introduce breaking changes if there is a major release of ngrx.

I will keep this strategy as long as I can effort to manage it.
If this changes in future there will be an announcement with all the information you need to migrate.

## Facade

You are totally a right, ngrx-ducks is a thin layer building a facade automatically.
There are some articles building ngrx facades as well.
But this is done with code generation and you even create more code that you have to maintain.
In my opinion, this is no real solution.

## Pick

The pick-Helper is intended to get you around the need of the `Store`-Dependencies.
You can pass whatever `selector` you like to get the information you need.

## Multiple Duck-Services

Since you need to dispatch actions to different slices of your store, you might end up with injecting multiple Ducks, right.

Maybe you can tell me a little bit more about your use case.
We may end up with an idea for a new API that offers better support.

---

I will document the version compatibility in the Docs. :)

**Comment by GregOnNet** [comment]
Explanation for ngrx/plaform support has benn addded: https://github.com/co-IT/co-it/commit/160e3b5fa205c169e320f1ca4c83ca6d7b74af24
